// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AttributeSchemaController from "./attribute_schema_controller"
application.register("attribute-schema", AttributeSchemaController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RichTextController from "./rich_text_controller"
application.register("rich-text", RichTextController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import TreeController from "./tree_controller"
application.register("tree", TreeController)
