FactoryBot.define do
  factory :requirement do
    section
    project { section.requirement_module.project }
    created_by factory: :user
    sequence(:title) { |n| "Requirement #{n}" }
    body { Faker::Lorem.paragraph }
    requirement_type { :functional }
    status { :draft }
    priority { :must_have }
    asil_level { :qm }
    custom_attributes { {} }
    # uid is auto-generated by the model

    trait :non_functional do
      requirement_type { :non_functional }
    end

    trait :safety do
      requirement_type { :safety }
      asil_level { :asil_b }
    end

    trait :approved do
      status { :approved }
    end

    trait :in_review do
      status { :in_review }
    end

    trait :obsolete do
      status { :obsolete }
    end

    trait :with_custom_attributes do
      custom_attributes do
        {
          "Safety Classification" => "ASIL-B",
          "Verification Method" => "Test"
        }
      end
    end
  end
end
